apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-omzn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-omzn
    app.kubernetes.io/part-of: test-app-jmoe
  name: test-component-omzn
  namespace: build-e2e-hacbs-vxsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-omzn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-omzn
    spec:
      containers:
      - image: quay.io/psturc/test-images:2270e409ddbe42b9a0ec35987bb0c3d0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
